import libcore.io.*;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(Suite.class)
@Suite.SuiteClasses({

    libcore.java.security.AccessControllerTest.class,
    libcore.java.security.KeyPairGeneratorTest.class,  //crash
    libcore.java.security.KeyStoreTest.class,
    libcore.java.security.MessageDigestTest.class,
    libcore.java.security.OldAlgorithmParameterGeneratorTest.class,
    libcore.java.security.OldDHTest.class,
    libcore.java.security.OldKeyPairGeneratorTestDH.class,
    libcore.java.security.ProviderTest.class,
    libcore.java.security.SecureRandomTest.class,
    libcore.java.security.SignatureTest.class,  //crash
    org.apache.harmony.security.tests.java.security.AlgorithmParameterGenerator1Test.class,
    org.apache.harmony.security.tests.java.security.AlgorithmParameterGenerator2Test.class,
    org.apache.harmony.security.tests.java.security.AlgorithmParametersSpiTest.class,
    org.apache.harmony.security.tests.java.security.AlgorithmParametersTest.class,
    org.apache.harmony.security.tests.java.security.CodeSignerTest.class,
    org.apache.harmony.security.tests.java.security.DigestExceptionTest.class,
    org.apache.harmony.security.tests.java.security.DigestInputStream2Test.class,
    org.apache.harmony.security.tests.java.security.DigestInputStreamTest.class,
    org.apache.harmony.security.tests.java.security.DigestOutputStreamTest.class,
    org.apache.harmony.security.tests.java.security.GeneralSecurityExceptionTest.class,
    org.apache.harmony.security.tests.java.security.GuardedObjectTest.class,
    org.apache.harmony.security.tests.java.security.Identity2Test.class,
    org.apache.harmony.security.tests.java.security.IdentityScope2Test.class,
    org.apache.harmony.security.tests.java.security.IdentityScopeTest.class,
    org.apache.harmony.security.tests.java.security.InvalidAlgorithmParameterExceptionTest.class,
    org.apache.harmony.security.tests.java.security.InvalidKeyExceptionTest.class,
    org.apache.harmony.security.tests.java.security.InvalidParameterExceptionTest.class,
    org.apache.harmony.security.tests.java.security.KeyExceptionTest.class,
    org.apache.harmony.security.tests.java.security.KeyFactory2Test.class, //crash
    org.apache.harmony.security.tests.java.security.KeyFactorySpiTest.class,
    org.apache.harmony.security.tests.java.security.KeyFactoryTest.class,
    org.apache.harmony.security.tests.java.security.KeyManagementExceptionTest.class,
    org.apache.harmony.security.tests.java.security.KeyPairGenerator1Test.class,
    org.apache.harmony.security.tests.java.security.KeyPairGenerator2Test.class,
    org.apache.harmony.security.tests.java.security.KeyPairGenerator3Test.class,
    org.apache.harmony.security.tests.java.security.KeyPairGenerator4Test.class,
    org.apache.harmony.security.tests.java.security.KeyPairGeneratorSpiTest.class,
    org.apache.harmony.security.tests.java.security.KeyPairTest.class,
    org.apache.harmony.security.tests.java.security.KeyRepTest.class,
    org.apache.harmony.security.tests.java.security.KeyRepTypeTest.class,
    org.apache.harmony.security.tests.java.security.KeyStore2Test.class,
    org.apache.harmony.security.tests.java.security.KeyStore3Test.class,
    org.apache.harmony.security.tests.java.security.KeyStore4Test.class,
    org.apache.harmony.security.tests.java.security.KeyStoreBuilderTest.class,
    org.apache.harmony.security.tests.java.security.KeyStoreExceptionTest.class,
    org.apache.harmony.security.tests.java.security.KeyStorePrivateKeyEntryTest.class,
    org.apache.harmony.security.tests.java.security.KeyStoreSpiTest.class,
    org.apache.harmony.security.tests.java.security.KeyStoreTest.class,
    org.apache.harmony.security.tests.java.security.KeyTest.class,
    org.apache.harmony.security.tests.java.security.KSCallbackHandlerProtectionTest.class,
    org.apache.harmony.security.tests.java.security.KSPasswordProtectionTest.class,
    org.apache.harmony.security.tests.java.security.KSPrivateKeyEntryTest.class,
    org.apache.harmony.security.tests.java.security.KSSecretKeyEntryTest.class,
    org.apache.harmony.security.tests.java.security.KSTrustedCertificateEntryTest.class,
    org.apache.harmony.security.tests.java.security.MessageDigest1Test.class,
    org.apache.harmony.security.tests.java.security.MessageDigest2Test.class,
    org.apache.harmony.security.tests.java.security.MessageDigestSpiTest.class,
    org.apache.harmony.security.tests.java.security.NoSuchAlgorithmExceptionTest.class,
    org.apache.harmony.security.tests.java.security.NoSuchProviderExceptionTest.class,
    org.apache.harmony.security.tests.java.security.PrivateKeyTest.class,
    org.apache.harmony.security.tests.java.security.PrivilegedActionTest.class,
    org.apache.harmony.security.tests.java.security.Provider2Test.class,
    org.apache.harmony.security.tests.java.security.ProviderExceptionTest.class,
    org.apache.harmony.security.tests.java.security.ProviderServiceTest.class,
    org.apache.harmony.security.tests.java.security.ProviderTest.class,
    org.apache.harmony.security.tests.java.security.PublicKeyTest.class,
    org.apache.harmony.security.tests.java.security.SecureRandom2Test.class,
    org.apache.harmony.security.tests.java.security.SecureRandomSpiTest.class,
    org.apache.harmony.security.tests.java.security.Security2Test.class,
    org.apache.harmony.security.tests.java.security.SecurityTest.class,
    org.apache.harmony.security.tests.java.security.Signature2Test.class,
    org.apache.harmony.security.tests.java.security.SignatureExceptionTest.class,
    org.apache.harmony.security.tests.java.security.SignatureSpiTest.class,
    org.apache.harmony.security.tests.java.security.SignatureTest.class,
    org.apache.harmony.security.tests.java.security.SignedObjectTest.class,
    org.apache.harmony.security.tests.java.security.SignerTest.class,
    org.apache.harmony.security.tests.java.security.TimestampTest.class,
    org.apache.harmony.security.tests.java.security.UnrecoverableEntryExceptionTest.class,
    org.apache.harmony.security.tests.java.security.UnrecoverableKeyExceptionTest.class,
    tests.java.security.AlgorithmParameterGeneratorSpiTest.class,
    tests.java.security.IdentityTest.class,
    tests.java.security.SecureClassLoaderTest.class,
    tests.java.security.SecureRandomTest.class,
    tests.targets.security.KeyStoreTestPKCS12.class,
    tests.targets.security.MessageDigestTestMD2.class,
    tests.targets.security.MessageDigestTestMD5.class,
    tests.targets.security.MessageDigestTestSHA1.class,
    tests.targets.security.MessageDigestTestSHA256.class,
    tests.targets.security.MessageDigestTestSHA384.class,
    tests.targets.security.MessageDigestTestSHA512.class,
    tests.targets.security.SecureRandomTestSHA1PRNG.class,
    tests.targets.security.SignatureTestMD2withRSA.class,

})
public class JunitExtJavaSecurity {
}