import libcore.io.*;
import org.junit.runner.RunWith;
import org.junit.runners.Suite;

@RunWith(Suite.class)
@Suite.SuiteClasses({

    org.apache.harmony.tests.java.nio.AbstractBufferTest.class,
    org.apache.harmony.tests.java.nio.BufferOverflowExceptionTest.class,
    org.apache.harmony.tests.java.nio.BufferUnderflowExceptionTest.class,
    org.apache.harmony.tests.java.nio.ByteBufferTest.class,
    org.apache.harmony.tests.java.nio.ByteOrderTest.class,
    org.apache.harmony.tests.java.nio.CharBufferTest.class,
    org.apache.harmony.tests.java.nio.DirectByteBufferTest.class,
    org.apache.harmony.tests.java.nio.DirectCharBufferTest.class,
    org.apache.harmony.tests.java.nio.DirectDoubleBufferTest.class,
    org.apache.harmony.tests.java.nio.DirectFloatBufferTest.class,
    org.apache.harmony.tests.java.nio.DirectIntBufferTest.class,
    org.apache.harmony.tests.java.nio.DirectLongBufferTest.class,
    org.apache.harmony.tests.java.nio.DirectShortBufferTest.class,
    org.apache.harmony.tests.java.nio.DoubleBufferTest.class,
    org.apache.harmony.tests.java.nio.DuplicateDirectByteBufferTest.class,
    org.apache.harmony.tests.java.nio.DuplicateHeapByteBufferTest.class,
    org.apache.harmony.tests.java.nio.DuplicateWrappedByteBufferTest.class,
    org.apache.harmony.tests.java.nio.FloatBufferTest.class,
    org.apache.harmony.tests.java.nio.HeapByteBufferTest.class,
    org.apache.harmony.tests.java.nio.HeapCharBufferTest.class,
    org.apache.harmony.tests.java.nio.HeapDoubleBufferTest.class,
    org.apache.harmony.tests.java.nio.HeapFloatBufferTest.class,
    org.apache.harmony.tests.java.nio.HeapIntBufferTest.class,
    org.apache.harmony.tests.java.nio.HeapLongBufferTest.class,
    org.apache.harmony.tests.java.nio.HeapShortBufferTest.class,
    org.apache.harmony.tests.java.nio.IntBufferTest.class,
    org.apache.harmony.tests.java.nio.InvalidMarkExceptionTest.class,
    org.apache.harmony.tests.java.nio.LongBufferTest.class,
    org.apache.harmony.tests.java.nio.MappedByteBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyBufferExceptionTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyCharBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyDirectByteBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyDoubleBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyFloatBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyHeapByteBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyHeapCharBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyHeapDoubleBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyHeapFloatBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyHeapIntBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyHeapLongBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyHeapShortBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyIntBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyLongBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyShortBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyWrappedByteBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyWrappedCharBufferTest1.class,
    org.apache.harmony.tests.java.nio.ReadOnlyWrappedDoubleBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyWrappedFloatBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyWrappedIntBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyWrappedLongBufferTest.class,
    org.apache.harmony.tests.java.nio.ReadOnlyWrappedShortBufferTest.class,
    org.apache.harmony.tests.java.nio.ShortBufferTest.class,
    org.apache.harmony.tests.java.nio.SliceDirectByteBufferTest.class,
    org.apache.harmony.tests.java.nio.SliceHeapByteBufferTest.class,
    org.apache.harmony.tests.java.nio.SliceWrappedByteBufferTest.class,
    org.apache.harmony.tests.java.nio.WrappedByteBufferTest.class,
    org.apache.harmony.tests.java.nio.WrappedDoubleBufferTest.class,
    org.apache.harmony.tests.java.nio.WrappedFloatBufferTest.class,
    org.apache.harmony.tests.java.nio.WrappedIntBufferTest.class,
    org.apache.harmony.tests.java.nio.WrappedLongBufferTest.class,
    org.apache.harmony.tests.java.nio.WrappedShortBufferTest.class,
    libcore.java.nio.BufferTest.class,
    libcore.java.nio.NoArrayTest.class,
    libcore.java.nio.OldAndroidNIOTest.class,
    libcore.java.nio.OldDirectIntBufferTest.class,
    libcore.java.nio.OldDirectShortBufferTest.class,

})

public class JunitExtJavaNio {
}